baseURL = "https://www.ampsicologiamadrid.com/"
languageCode = "es"
title = "Psicóloga Madrid Centro"
publishDir = "dist"

[params]
    seoTitleSuffix = "Psicóloga Especialista en Madrid"
    name = "Alaitz Martínez Latorre"
    description = "AM Psicología Madrid, gabinete de psicología clínica para niños y adultos. Psicólogo infantil, terapia de pareja, tratamiento de depresión, ansiedad, adicciones..."
    email = "contacto@ampsicologiamadrid.com"
    phone = "915 220 679"
    cellphone = "686 898 494"
    phones = "915 220 679 - 686 898 494"
    address = """Calle de Los Madrazo 28, 1º izq
    28014 Madrid (Madrid)"""
    year = 2018
    background = ""
    favicon = "images/favicon.gif"
    DateForm = "January 2, 2006"

    showSubheader = true
    showTerapias = true
    showBlog = true

    footerEnableContact = true
    footerEnableFollowme = true

[params.google.analytics]
    trackerID = "UA-80776329-1"

[params.google.tagManager]
    globalTag = "AW-871028697"
    sendTo = "AW-871028697/qmBACIX58pQBENmvq58D"

[[params.social]]
	title = "twitter"
	url = "https://twitter.com/am_psicologia"
    icon = "fa-twitter-square"
    info =true
    footer = true
    network = "twitter"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/ampsicologiamadrid"
    icon = "fa-facebook-square"
    info =true
    footer = true
    network = "facebook"

[[params.social]]
	title = "linkedin"
	url = "https://es.linkedin.com/in/alaitz-mart%C3%ADnez-latorre-a8b8788a"
    icon = "fa-linkedin-square"
    info =true
    footer = true
    network = "linkedin"

[[params.social]]
	title = "email"
	url = "mailto:contacto@ampsicologia.es"
    icon = "fa-envelope"
    footer = false
    network = "email"

[[menu.main]]
    name = "sobre mi"
    url = "/sobre-mi/"
    weight = 1

[[menu.main]]
    name = "terapias"
    url = "#"
    weight = 2

[[menu.main]]
    parent = "terapias"
    name = "adultos"
    url = "/terapias/adultos"
    weight = 1

[[menu.main]]
    parent = "terapias"
    name = "pareja"
    url = "/terapias/pareja"
    weight = 2

[[menu.main]]
    parent = "terapias"
    name = "infantil"
    url = "/terapias/infantil"
    weight = 3

[[menu.main]]
    parent = "terapias"
    name = "familia"
    url = "/terapias/familia"
    weight = 4

[[menu.main]]
    parent = "terapias"
    name = "coaching"
    url = "/terapias/coaching"
    weight = 5

[[menu.main]]
    parent = "terapias"
    name = "informes"
    url = "/terapias/informes"
    weight = 6

[[menu.main]]
    name = "areas intervención"
    url = "#"
    weight = 3

[[menu.main]]
    parent = "areas intervención"
    name = "adiciones"
    url = "/areas-intervencion/adicciones"
    weight = 1

[[menu.main]]
    parent = "areas intervención"
    name = "ansiedad"
    url = "/areas-intervencion/ansiedad"
    weight = 2

[[menu.main]]
    parent = "areas intervención"
    name = "depresion"
    url = "/areas-intervencion/depresion"
    weight = 3

[[menu.main]]
    parent = "areas intervención"
    name = "duelos"
    url = "/areas-intervencion/duelos"
    weight = 4

[[menu.main]]
    parent = "areas intervención"
    name = "estres"
    url = "/areas-intervencion/estres"
    weight = 5

[[menu.main]]
    parent = "areas intervención"
    name = "fobias"
    url = "/areas-intervencion/fobias"
    weight = 6

[[menu.main]]
    parent = "areas intervención"
    name = "obsesiones"
    url = "/areas-intervencion/obsesiones"
    weight = 7

[[menu.main]]
    parent = "areas intervención"
    name = "alimentacion"
    url = "/areas-intervencion/alimentacion"
    weight = 8

[[menu.main]]
    parent = "areas intervención"
    name = "personalidad"
    url = "/areas-intervencion/personalidad"
    weight = 9

[[menu.main]]
    parent = "areas intervención"
    name = "sueño"
    url = "/areas-intervencion/sueno"
    weight = 10

[[menu.main]]
    name = "tarifas"
    url = "/tarifas/"
    weight = 4

[[menu.main]]
    name = "contacto"
    url = "/contacto/"
    weight = 5

[[menu.main]]
    name = "blog"
    url = "/posts/"
    weight = 6